# Generated by Django 5.1.2 on 2024-11-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='news_images/'),
        ),
    ]
