# Generated by Django 5.1.2 on 2024-11-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_league_name_match_score_away_match_score_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='api_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
