# Generated by Django 5.1.2 on 2024-11-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_league_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='api_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
