# Generated by Django 5.1.2 on 2024-11-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_alter_league_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=127),
        ),
    ]
