# Generated by Django 5.1.2 on 2024-11-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0008_alter_league_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='code',
            field=models.CharField(default='tep', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='logo_link',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
