# Generated by Django 5.1.2 on 2024-11-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0009_league_code_league_logo_link_alter_league_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='stadium',
            field=models.CharField(default='', max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='tla',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.CharField(max_length=127),
        ),
    ]
