# Generated by Django 5.1.2 on 2024-11-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0010_team_stadium_team_tla_alter_team_logo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('home_team', 'away_team', 'date'), name='unique_match'),
        ),
    ]
